# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .cert_manager import *
from .provider import *
from ._inputs import *
from . import outputs
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "kubernetes-cert-manager",
  "mod": "index",
  "fqn": "pulumi_kubernetes_cert_manager",
  "classes": {
   "kubernetes-cert-manager:index:CertManager": "CertManager"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "kubernetes-cert-manager",
  "token": "pulumi:providers:kubernetes-cert-manager",
  "fqn": "pulumi_kubernetes_cert_manager",
  "class": "Provider"
 }
]
"""
)
