# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'ReleaseStatus',
]

@pulumi.output_type
class ReleaseStatus(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "appVersion":
            suggest = "app_version"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ReleaseStatus. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ReleaseStatus.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ReleaseStatus.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 app_version: _builtins.str,
                 chart: _builtins.str,
                 name: _builtins.str,
                 namespace: _builtins.str,
                 revision: _builtins.int,
                 status: _builtins.str,
                 version: _builtins.str):
        """
        :param _builtins.str app_version: The version number of the application being deployed.
        :param _builtins.str chart: The name of the chart.
        :param _builtins.str name: Name is the name of the release.
        :param _builtins.str namespace: Namespace is the kubernetes namespace of the release.
        :param _builtins.int revision: Version is an int32 which represents the version of the release.
        :param _builtins.str status: Status of the release.
        :param _builtins.str version: A SemVer 2 conformant version string of the chart.
        """
        pulumi.set(__self__, "app_version", app_version)
        pulumi.set(__self__, "chart", chart)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "namespace", namespace)
        pulumi.set(__self__, "revision", revision)
        pulumi.set(__self__, "status", status)
        pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter(name="appVersion")
    def app_version(self) -> _builtins.str:
        """
        The version number of the application being deployed.
        """
        return pulumi.get(self, "app_version")

    @_builtins.property
    @pulumi.getter
    def chart(self) -> _builtins.str:
        """
        The name of the chart.
        """
        return pulumi.get(self, "chart")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        Name is the name of the release.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> _builtins.str:
        """
        Namespace is the kubernetes namespace of the release.
        """
        return pulumi.get(self, "namespace")

    @_builtins.property
    @pulumi.getter
    def revision(self) -> _builtins.int:
        """
        Version is an int32 which represents the version of the release.
        """
        return pulumi.get(self, "revision")

    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str:
        """
        Status of the release.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def version(self) -> _builtins.str:
        """
        A SemVer 2 conformant version string of the chart.
        """
        return pulumi.get(self, "version")


