# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_cert_manager_resources.acme as __acme
    acme = __acme
    import pulumi_cert_manager_resources.certmanager as __certmanager
    certmanager = __certmanager
    import pulumi_cert_manager_resources.meta as __meta
    meta = __meta
else:
    acme = _utilities.lazy_import('pulumi_cert_manager.acme')
    certmanager = _utilities.lazy_import('pulumi_cert_manager.certmanager')
    meta = _utilities.lazy_import('pulumi_cert_manager.meta')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "cert_manager",
  "mod": "acme.cert-manager.io/v1",
  "fqn": "pulumi_cert_manager.acme.v1",
  "classes": {
   "kubernetes:acme.cert-manager.io/v1:Challenge": "Challenge",
   "kubernetes:acme.cert-manager.io/v1:Order": "Order"
  }
 },
 {
  "pkg": "cert_manager",
  "mod": "cert-manager.io/v1",
  "fqn": "pulumi_cert_manager.certmanager.v1",
  "classes": {
   "kubernetes:cert-manager.io/v1:Certificate": "Certificate",
   "kubernetes:cert-manager.io/v1:CertificateRequest": "CertificateRequest",
   "kubernetes:cert-manager.io/v1:ClusterIssuer": "ClusterIssuer",
   "kubernetes:cert-manager.io/v1:Issuer": "Issuer"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "cert_manager",
  "token": "pulumi:providers:crds",
  "fqn": "pulumi_cert_manager",
  "class": "Provider"
 }
]
"""
)
