# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import errno
from setuptools import setup, find_packages
from setuptools.command.install import install
from subprocess import check_call


VERSION = "1.0.0a0+dev"
def readme():
    try:
        with open('README.md', encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        return "kubernetes-cert-manager Pulumi Package - Development Version"


setup(name='pulumi_kubernetes_cert_manager',
      python_requires='>=3.8',
      version=VERSION,
      description="Strongly-typed Cert Manager installation",
      long_description=readme(),
      long_description_content_type='text/markdown',
      keywords='pulumi kubernetes cert-manager kind/component category/infrastructure',
      url='https://pulumi.io',
      project_urls={
          'Repository': 'https://github.com/pulumi/pulumi-kubernetes-cert-manager'
      },
      license='Apache-2.0',
      packages=find_packages(),
      package_data={
          'pulumi_kubernetes_cert_manager': [
              'py.typed',
              'pulumi-plugin.json',
          ]
      },
      install_requires=[
          'parver>=0.2.1',
          'pulumi>=3.0.0,<4.0.0',
          'pulumi-kubernetes>=3.7.1,<5.0.0',
          'semver>=2.8.1'
      ],
      zip_safe=False)
