// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import * as pulumiKubernetes from "@pulumi/kubernetes";

export interface ReleaseStatus {
    /**
     * The version number of the application being deployed.
     */
    appVersion: string;
    /**
     * The name of the chart.
     */
    chart: string;
    /**
     * Name is the name of the release.
     */
    name: string;
    /**
     * Namespace is the kubernetes namespace of the release.
     */
    namespace: string;
    /**
     * Version is an int32 which represents the version of the release.
     */
    revision: number;
    /**
     * Status of the release.
     */
    status: string;
    /**
     * A SemVer 2 conformant version string of the chart.
     */
    version: string;
}

