// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetescertmanager.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.kubernetescertmanager.inputs.CertManagerPrometheusServiceMonitorArgs;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CertManagerPrometheusArgs extends com.pulumi.resources.ResourceArgs {

    public static final CertManagerPrometheusArgs Empty = new CertManagerPrometheusArgs();

    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    @Import(name="serviceMonitor")
    private @Nullable Output<CertManagerPrometheusServiceMonitorArgs> serviceMonitor;

    public Optional<Output<CertManagerPrometheusServiceMonitorArgs>> serviceMonitor() {
        return Optional.ofNullable(this.serviceMonitor);
    }

    private CertManagerPrometheusArgs() {}

    private CertManagerPrometheusArgs(CertManagerPrometheusArgs $) {
        this.enabled = $.enabled;
        this.serviceMonitor = $.serviceMonitor;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CertManagerPrometheusArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CertManagerPrometheusArgs $;

        public Builder() {
            $ = new CertManagerPrometheusArgs();
        }

        public Builder(CertManagerPrometheusArgs defaults) {
            $ = new CertManagerPrometheusArgs(Objects.requireNonNull(defaults));
        }

        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        public Builder serviceMonitor(@Nullable Output<CertManagerPrometheusServiceMonitorArgs> serviceMonitor) {
            $.serviceMonitor = serviceMonitor;
            return this;
        }

        public Builder serviceMonitor(CertManagerPrometheusServiceMonitorArgs serviceMonitor) {
            return serviceMonitor(Output.of(serviceMonitor));
        }

        public CertManagerPrometheusArgs build() {
            return $;
        }
    }

}
