// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetescertmanager.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CertManagerWebhookURLArgs extends com.pulumi.resources.ResourceArgs {

    public static final CertManagerWebhookURLArgs Empty = new CertManagerWebhookURLArgs();

    @Import(name="host")
    private @Nullable Output<String> host;

    public Optional<Output<String>> host() {
        return Optional.ofNullable(this.host);
    }

    private CertManagerWebhookURLArgs() {}

    private CertManagerWebhookURLArgs(CertManagerWebhookURLArgs $) {
        this.host = $.host;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CertManagerWebhookURLArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CertManagerWebhookURLArgs $;

        public Builder() {
            $ = new CertManagerWebhookURLArgs();
        }

        public Builder(CertManagerWebhookURLArgs defaults) {
            $ = new CertManagerWebhookURLArgs(Objects.requireNonNull(defaults));
        }

        public Builder host(@Nullable Output<String> host) {
            $.host = host;
            return this;
        }

        public Builder host(String host) {
            return host(Output.of(host));
        }

        public CertManagerWebhookURLArgs build() {
            return $;
        }
    }

}
