// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetescertmanager.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CertManagerServiceAccountArgs extends com.pulumi.resources.ResourceArgs {

    public static final CertManagerServiceAccountArgs Empty = new CertManagerServiceAccountArgs();

    /**
     * Optional additional annotations to add to the controller&#39;s ServiceAccount.
     * 
     */
    @Import(name="annotations")
    private @Nullable Output<Map<String,String>> annotations;

    /**
     * @return Optional additional annotations to add to the controller&#39;s ServiceAccount.
     * 
     */
    public Optional<Output<Map<String,String>>> annotations() {
        return Optional.ofNullable(this.annotations);
    }

    /**
     * Automount API credentials for a Service Account.
     * 
     */
    @Import(name="automountServiceAccountToken")
    private @Nullable Output<Boolean> automountServiceAccountToken;

    /**
     * @return Automount API credentials for a Service Account.
     * 
     */
    public Optional<Output<Boolean>> automountServiceAccountToken() {
        return Optional.ofNullable(this.automountServiceAccountToken);
    }

    /**
     * Specifies whether a service account should be created
     * 
     */
    @Import(name="create")
    private @Nullable Output<Boolean> create;

    /**
     * @return Specifies whether a service account should be created
     * 
     */
    public Optional<Output<Boolean>> create() {
        return Optional.ofNullable(this.create);
    }

    /**
     * The name of the service account to use. If not set and create is true, a name is generated using the fullname template.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the service account to use. If not set and create is true, a name is generated using the fullname template.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    private CertManagerServiceAccountArgs() {}

    private CertManagerServiceAccountArgs(CertManagerServiceAccountArgs $) {
        this.annotations = $.annotations;
        this.automountServiceAccountToken = $.automountServiceAccountToken;
        this.create = $.create;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CertManagerServiceAccountArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CertManagerServiceAccountArgs $;

        public Builder() {
            $ = new CertManagerServiceAccountArgs();
        }

        public Builder(CertManagerServiceAccountArgs defaults) {
            $ = new CertManagerServiceAccountArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param annotations Optional additional annotations to add to the controller&#39;s ServiceAccount.
         * 
         * @return builder
         * 
         */
        public Builder annotations(@Nullable Output<Map<String,String>> annotations) {
            $.annotations = annotations;
            return this;
        }

        /**
         * @param annotations Optional additional annotations to add to the controller&#39;s ServiceAccount.
         * 
         * @return builder
         * 
         */
        public Builder annotations(Map<String,String> annotations) {
            return annotations(Output.of(annotations));
        }

        /**
         * @param automountServiceAccountToken Automount API credentials for a Service Account.
         * 
         * @return builder
         * 
         */
        public Builder automountServiceAccountToken(@Nullable Output<Boolean> automountServiceAccountToken) {
            $.automountServiceAccountToken = automountServiceAccountToken;
            return this;
        }

        /**
         * @param automountServiceAccountToken Automount API credentials for a Service Account.
         * 
         * @return builder
         * 
         */
        public Builder automountServiceAccountToken(Boolean automountServiceAccountToken) {
            return automountServiceAccountToken(Output.of(automountServiceAccountToken));
        }

        /**
         * @param create Specifies whether a service account should be created
         * 
         * @return builder
         * 
         */
        public Builder create(@Nullable Output<Boolean> create) {
            $.create = create;
            return this;
        }

        /**
         * @param create Specifies whether a service account should be created
         * 
         * @return builder
         * 
         */
        public Builder create(Boolean create) {
            return create(Output.of(create));
        }

        /**
         * @param name The name of the service account to use. If not set and create is true, a name is generated using the fullname template.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the service account to use. If not set and create is true, a name is generated using the fullname template.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public CertManagerServiceAccountArgs build() {
            return $;
        }
    }

}
