// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetescertmanager.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CertManagerIngressShimArgs extends com.pulumi.resources.ResourceArgs {

    public static final CertManagerIngressShimArgs Empty = new CertManagerIngressShimArgs();

    @Import(name="defaultIssuerGroup")
    private @Nullable Output<String> defaultIssuerGroup;

    public Optional<Output<String>> defaultIssuerGroup() {
        return Optional.ofNullable(this.defaultIssuerGroup);
    }

    @Import(name="defaultIssuerKind")
    private @Nullable Output<String> defaultIssuerKind;

    public Optional<Output<String>> defaultIssuerKind() {
        return Optional.ofNullable(this.defaultIssuerKind);
    }

    @Import(name="defaultIssuerName")
    private @Nullable Output<String> defaultIssuerName;

    public Optional<Output<String>> defaultIssuerName() {
        return Optional.ofNullable(this.defaultIssuerName);
    }

    private CertManagerIngressShimArgs() {}

    private CertManagerIngressShimArgs(CertManagerIngressShimArgs $) {
        this.defaultIssuerGroup = $.defaultIssuerGroup;
        this.defaultIssuerKind = $.defaultIssuerKind;
        this.defaultIssuerName = $.defaultIssuerName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CertManagerIngressShimArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CertManagerIngressShimArgs $;

        public Builder() {
            $ = new CertManagerIngressShimArgs();
        }

        public Builder(CertManagerIngressShimArgs defaults) {
            $ = new CertManagerIngressShimArgs(Objects.requireNonNull(defaults));
        }

        public Builder defaultIssuerGroup(@Nullable Output<String> defaultIssuerGroup) {
            $.defaultIssuerGroup = defaultIssuerGroup;
            return this;
        }

        public Builder defaultIssuerGroup(String defaultIssuerGroup) {
            return defaultIssuerGroup(Output.of(defaultIssuerGroup));
        }

        public Builder defaultIssuerKind(@Nullable Output<String> defaultIssuerKind) {
            $.defaultIssuerKind = defaultIssuerKind;
            return this;
        }

        public Builder defaultIssuerKind(String defaultIssuerKind) {
            return defaultIssuerKind(Output.of(defaultIssuerKind));
        }

        public Builder defaultIssuerName(@Nullable Output<String> defaultIssuerName) {
            $.defaultIssuerName = defaultIssuerName;
            return this;
        }

        public Builder defaultIssuerName(String defaultIssuerName) {
            return defaultIssuerName(Output.of(defaultIssuerName));
        }

        public CertManagerIngressShimArgs build() {
            return $;
        }
    }

}
