// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetescertmanager.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CertManagerGlobalPodSecurityPolicyArgs extends com.pulumi.resources.ResourceArgs {

    public static final CertManagerGlobalPodSecurityPolicyArgs Empty = new CertManagerGlobalPodSecurityPolicyArgs();

    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    @Import(name="useAppArmor")
    private @Nullable Output<Boolean> useAppArmor;

    public Optional<Output<Boolean>> useAppArmor() {
        return Optional.ofNullable(this.useAppArmor);
    }

    private CertManagerGlobalPodSecurityPolicyArgs() {}

    private CertManagerGlobalPodSecurityPolicyArgs(CertManagerGlobalPodSecurityPolicyArgs $) {
        this.enabled = $.enabled;
        this.useAppArmor = $.useAppArmor;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CertManagerGlobalPodSecurityPolicyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CertManagerGlobalPodSecurityPolicyArgs $;

        public Builder() {
            $ = new CertManagerGlobalPodSecurityPolicyArgs();
        }

        public Builder(CertManagerGlobalPodSecurityPolicyArgs defaults) {
            $ = new CertManagerGlobalPodSecurityPolicyArgs(Objects.requireNonNull(defaults));
        }

        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        public Builder useAppArmor(@Nullable Output<Boolean> useAppArmor) {
            $.useAppArmor = useAppArmor;
            return this;
        }

        public Builder useAppArmor(Boolean useAppArmor) {
            return useAppArmor(Output.of(useAppArmor));
        }

        public CertManagerGlobalPodSecurityPolicyArgs build() {
            return $;
        }
    }

}
