// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetescertmanager.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CertManagerStartupAPICheckRBACArgs extends com.pulumi.resources.ResourceArgs {

    public static final CertManagerStartupAPICheckRBACArgs Empty = new CertManagerStartupAPICheckRBACArgs();

    /**
     * annotations for the startup API Check job RBAC and PSP resources
     * 
     */
    @Import(name="annotations")
    private @Nullable Output<Map<String,String>> annotations;

    /**
     * @return annotations for the startup API Check job RBAC and PSP resources
     * 
     */
    public Optional<Output<Map<String,String>>> annotations() {
        return Optional.ofNullable(this.annotations);
    }

    private CertManagerStartupAPICheckRBACArgs() {}

    private CertManagerStartupAPICheckRBACArgs(CertManagerStartupAPICheckRBACArgs $) {
        this.annotations = $.annotations;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CertManagerStartupAPICheckRBACArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CertManagerStartupAPICheckRBACArgs $;

        public Builder() {
            $ = new CertManagerStartupAPICheckRBACArgs();
        }

        public Builder(CertManagerStartupAPICheckRBACArgs defaults) {
            $ = new CertManagerStartupAPICheckRBACArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param annotations annotations for the startup API Check job RBAC and PSP resources
         * 
         * @return builder
         * 
         */
        public Builder annotations(@Nullable Output<Map<String,String>> annotations) {
            $.annotations = annotations;
            return this;
        }

        /**
         * @param annotations annotations for the startup API Check job RBAC and PSP resources
         * 
         * @return builder
         * 
         */
        public Builder annotations(Map<String,String> annotations) {
            return annotations(Output.of(annotations));
        }

        public CertManagerStartupAPICheckRBACArgs build() {
            return $;
        }
    }

}
