// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetescertmanager.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.kubernetes.core.v1.inputs.LocalObjectReferenceArgs;
import com.pulumi.kubernetescertmanager.inputs.CertManagerGlobalLeaderElectionArgs;
import com.pulumi.kubernetescertmanager.inputs.CertManagerGlobalPodSecurityPolicyArgs;
import com.pulumi.kubernetescertmanager.inputs.CertManagerGlobalRbacArgs;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CertManagerGlobalArgs extends com.pulumi.resources.ResourceArgs {

    public static final CertManagerGlobalArgs Empty = new CertManagerGlobalArgs();

    /**
     * Reference to one or more secrets to be used when pulling images. ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
     * 
     */
    @Import(name="imagePullSecrets")
    private @Nullable Output<List<LocalObjectReferenceArgs>> imagePullSecrets;

    /**
     * @return Reference to one or more secrets to be used when pulling images. ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
     * 
     */
    public Optional<Output<List<LocalObjectReferenceArgs>>> imagePullSecrets() {
        return Optional.ofNullable(this.imagePullSecrets);
    }

    @Import(name="leaderElection")
    private @Nullable Output<CertManagerGlobalLeaderElectionArgs> leaderElection;

    public Optional<Output<CertManagerGlobalLeaderElectionArgs>> leaderElection() {
        return Optional.ofNullable(this.leaderElection);
    }

    /**
     * Set the verbosity of cert-manager. Range of 0 - 6 with 6 being the most verbose.
     * 
     */
    @Import(name="logLevel")
    private @Nullable Output<Integer> logLevel;

    /**
     * @return Set the verbosity of cert-manager. Range of 0 - 6 with 6 being the most verbose.
     * 
     */
    public Optional<Output<Integer>> logLevel() {
        return Optional.ofNullable(this.logLevel);
    }

    @Import(name="podSecurityPolicy")
    private @Nullable Output<CertManagerGlobalPodSecurityPolicyArgs> podSecurityPolicy;

    public Optional<Output<CertManagerGlobalPodSecurityPolicyArgs>> podSecurityPolicy() {
        return Optional.ofNullable(this.podSecurityPolicy);
    }

    /**
     * Optional priority class to be used for the cert-manager pods.
     * 
     */
    @Import(name="priorityClassName")
    private @Nullable Output<String> priorityClassName;

    /**
     * @return Optional priority class to be used for the cert-manager pods.
     * 
     */
    public Optional<Output<String>> priorityClassName() {
        return Optional.ofNullable(this.priorityClassName);
    }

    @Import(name="rbac")
    private @Nullable Output<CertManagerGlobalRbacArgs> rbac;

    public Optional<Output<CertManagerGlobalRbacArgs>> rbac() {
        return Optional.ofNullable(this.rbac);
    }

    private CertManagerGlobalArgs() {}

    private CertManagerGlobalArgs(CertManagerGlobalArgs $) {
        this.imagePullSecrets = $.imagePullSecrets;
        this.leaderElection = $.leaderElection;
        this.logLevel = $.logLevel;
        this.podSecurityPolicy = $.podSecurityPolicy;
        this.priorityClassName = $.priorityClassName;
        this.rbac = $.rbac;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CertManagerGlobalArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CertManagerGlobalArgs $;

        public Builder() {
            $ = new CertManagerGlobalArgs();
        }

        public Builder(CertManagerGlobalArgs defaults) {
            $ = new CertManagerGlobalArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param imagePullSecrets Reference to one or more secrets to be used when pulling images. ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
         * 
         * @return builder
         * 
         */
        public Builder imagePullSecrets(@Nullable Output<List<LocalObjectReferenceArgs>> imagePullSecrets) {
            $.imagePullSecrets = imagePullSecrets;
            return this;
        }

        /**
         * @param imagePullSecrets Reference to one or more secrets to be used when pulling images. ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
         * 
         * @return builder
         * 
         */
        public Builder imagePullSecrets(List<LocalObjectReferenceArgs> imagePullSecrets) {
            return imagePullSecrets(Output.of(imagePullSecrets));
        }

        /**
         * @param imagePullSecrets Reference to one or more secrets to be used when pulling images. ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
         * 
         * @return builder
         * 
         */
        public Builder imagePullSecrets(LocalObjectReferenceArgs... imagePullSecrets) {
            return imagePullSecrets(List.of(imagePullSecrets));
        }

        public Builder leaderElection(@Nullable Output<CertManagerGlobalLeaderElectionArgs> leaderElection) {
            $.leaderElection = leaderElection;
            return this;
        }

        public Builder leaderElection(CertManagerGlobalLeaderElectionArgs leaderElection) {
            return leaderElection(Output.of(leaderElection));
        }

        /**
         * @param logLevel Set the verbosity of cert-manager. Range of 0 - 6 with 6 being the most verbose.
         * 
         * @return builder
         * 
         */
        public Builder logLevel(@Nullable Output<Integer> logLevel) {
            $.logLevel = logLevel;
            return this;
        }

        /**
         * @param logLevel Set the verbosity of cert-manager. Range of 0 - 6 with 6 being the most verbose.
         * 
         * @return builder
         * 
         */
        public Builder logLevel(Integer logLevel) {
            return logLevel(Output.of(logLevel));
        }

        public Builder podSecurityPolicy(@Nullable Output<CertManagerGlobalPodSecurityPolicyArgs> podSecurityPolicy) {
            $.podSecurityPolicy = podSecurityPolicy;
            return this;
        }

        public Builder podSecurityPolicy(CertManagerGlobalPodSecurityPolicyArgs podSecurityPolicy) {
            return podSecurityPolicy(Output.of(podSecurityPolicy));
        }

        /**
         * @param priorityClassName Optional priority class to be used for the cert-manager pods.
         * 
         * @return builder
         * 
         */
        public Builder priorityClassName(@Nullable Output<String> priorityClassName) {
            $.priorityClassName = priorityClassName;
            return this;
        }

        /**
         * @param priorityClassName Optional priority class to be used for the cert-manager pods.
         * 
         * @return builder
         * 
         */
        public Builder priorityClassName(String priorityClassName) {
            return priorityClassName(Output.of(priorityClassName));
        }

        public Builder rbac(@Nullable Output<CertManagerGlobalRbacArgs> rbac) {
            $.rbac = rbac;
            return this;
        }

        public Builder rbac(CertManagerGlobalRbacArgs rbac) {
            return rbac(Output.of(rbac));
        }

        public CertManagerGlobalArgs build() {
            return $;
        }
    }

}
