// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.KubernetesCertManager.Inputs
{

    public sealed class CertManagerStartupAPICheckArgs : global::Pulumi.ResourceArgs
    {
        [Input("affinity")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Core.V1.AffinityArgs>? Affinity { get; set; }

        /// <summary>
        /// Job backoffLimit
        /// </summary>
        [Input("backoffLimit")]
        public Input<int>? BackoffLimit { get; set; }

        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("extraArgs")]
        private InputList<string>? _extraArgs;

        /// <summary>
        /// Optional additional arguments for startupapicheck
        /// </summary>
        public InputList<string> ExtraArgs
        {
            get => _extraArgs ?? (_extraArgs = new InputList<string>());
            set => _extraArgs = value;
        }

        [Input("image")]
        public Input<Inputs.CertManagerImageArgs>? Image { get; set; }

        [Input("jobAnnotations")]
        private InputMap<string>? _jobAnnotations;

        /// <summary>
        /// Optional additional annotations to add to the startupapicheck Job
        /// </summary>
        public InputMap<string> JobAnnotations
        {
            get => _jobAnnotations ?? (_jobAnnotations = new InputMap<string>());
            set => _jobAnnotations = value;
        }

        [Input("nodeSelector")]
        private InputMap<string>? _nodeSelector;
        public InputMap<string> NodeSelector
        {
            get => _nodeSelector ?? (_nodeSelector = new InputMap<string>());
            set => _nodeSelector = value;
        }

        [Input("podAnnotations")]
        private InputMap<string>? _podAnnotations;

        /// <summary>
        /// Optional additional annotations to add to the startupapicheck Pods
        /// </summary>
        public InputMap<string> PodAnnotations
        {
            get => _podAnnotations ?? (_podAnnotations = new InputMap<string>());
            set => _podAnnotations = value;
        }

        [Input("podLabels")]
        private InputMap<string>? _podLabels;

        /// <summary>
        /// Optional additional labels to add to the startupapicheck Pods
        /// </summary>
        public InputMap<string> PodLabels
        {
            get => _podLabels ?? (_podLabels = new InputMap<string>());
            set => _podLabels = value;
        }

        [Input("rbac")]
        public Input<Inputs.CertManagerStartupAPICheckRBACArgs>? Rbac { get; set; }

        [Input("resources")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Core.V1.ResourceRequirementsArgs>? Resources { get; set; }

        /// <summary>
        /// Pod Security Context to be set on the startupapicheck component Pod. ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
        /// </summary>
        [Input("securityContext")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Core.V1.PodSecurityContextArgs>? SecurityContext { get; set; }

        [Input("serviceAccount")]
        public Input<Inputs.CertManagerServiceAccountArgs>? ServiceAccount { get; set; }

        /// <summary>
        /// Timeout for 'kubectl check api' command
        /// </summary>
        [Input("timeout")]
        public Input<string>? Timeout { get; set; }

        [Input("tolerations")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Core.V1.TolerationArgs>? _tolerations;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Core.V1.TolerationArgs> Tolerations
        {
            get => _tolerations ?? (_tolerations = new InputList<Pulumi.Kubernetes.Types.Inputs.Core.V1.TolerationArgs>());
            set => _tolerations = value;
        }

        public CertManagerStartupAPICheckArgs()
        {
        }
        public static new CertManagerStartupAPICheckArgs Empty => new CertManagerStartupAPICheckArgs();
    }
}
