// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.KubernetesCertManager.Inputs
{

    public sealed class CertManagerPrometheusArgs : global::Pulumi.ResourceArgs
    {
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("serviceMonitor")]
        public Input<Inputs.CertManagerPrometheusServiceMonitorArgs>? ServiceMonitor { get; set; }

        public CertManagerPrometheusArgs()
        {
        }
        public static new CertManagerPrometheusArgs Empty => new CertManagerPrometheusArgs();
    }
}
