// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.KubernetesCertManager.Inputs
{

    public sealed class CertManagerImageArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Setting a digest will override any tag, e.g. `digest: sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20`.
        /// </summary>
        [Input("digest")]
        public Input<string>? Digest { get; set; }

        [Input("pullPolicy")]
        public Input<string>? PullPolicy { get; set; }

        /// <summary>
        /// You can manage a registry with `registry: quay.io`.
        /// </summary>
        [Input("registry")]
        public Input<string>? Registry { get; set; }

        /// <summary>
        /// You can manage a registry with `repository: jetstack/cert-manager-controller`.
        /// </summary>
        [Input("repository")]
        public Input<string>? Repository { get; set; }

        /// <summary>
        /// Override the image tag to deploy by setting this variable. If no value is set, the chart's appVersion will be used.
        /// </summary>
        [Input("tag")]
        public Input<string>? Tag { get; set; }

        public CertManagerImageArgs()
        {
        }
    }
}
