// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.KubernetesCertManager.Inputs
{

    public sealed class CertManagerCrdsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable customization of the installation of CRDs. Cannot be enabled with installCRDs.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Keep CRDs on chart uninstall. Setting to false will remove CRDs when the chart is removed.
        /// </summary>
        [Input("keep")]
        public Input<bool>? Keep { get; set; }

        public CertManagerCrdsArgs()
        {
            Keep = false;
        }
        public static new CertManagerCrdsArgs Empty => new CertManagerCrdsArgs();
    }
}
