// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.KubernetesCertManager.Inputs
{

    public sealed class CertManagerCrdsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable CRDs installation
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Keep CRDs after chart uninstall
        /// </summary>
        [Input("keep")]
        public Input<bool>? Keep { get; set; }

        public CertManagerCrdsArgs()
        {
        }
        public static new CertManagerCrdsArgs Empty => new CertManagerCrdsArgs();
    }
}
