// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.KubernetesCertManager.Inputs
{

    public sealed class CertManagerGlobalPodSecurityPolicyArgs : global::Pulumi.ResourceArgs
    {
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("useAppArmor")]
        public Input<bool>? UseAppArmor { get; set; }

        public CertManagerGlobalPodSecurityPolicyArgs()
        {
        }
        public static new CertManagerGlobalPodSecurityPolicyArgs Empty => new CertManagerGlobalPodSecurityPolicyArgs();
    }
}
